name: sound_mind
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  go_router: 
  hive_flutter: 
  bloc_test: 
  mocktail: 
  gap: 
  flutter_dotenv:
  loading_animation_widget: 
  image_picker: 
  bottom_sheet: 
  smooth_page_indicator: 
  cached_network_image: 
  pinput: 
  permission_handler: 
  intl: 
  equatable: 
  dartz: 
  bloc: 
  flutter_bloc: 
  get_it: 
  flutter_gen: 
  dartx: 
  url_launcher: ^6.1.9
  dio:
  # flutter_local_notifications: 
  firebase_core: 
  firebase_messaging: 
  auto_size_text: ^3.0.0
  flutter_animate: ^4.5.0
  flutter_svg: ^2.0.10+1
  vector_graphics: ^1.1.11+1
  flutter_animation_progress_bar: ^2.3.1
  intl_phone_number_field: ^0.2.0
  local_auth: ^2.3.0
  pin_input_text_field: ^4.5.2
  flutterwave_standard_smart: ^1.0.4
  webview_flutter: ^4.10.0
  signalr_flutter: ^0.2.0
  signalr_netcore: ^1.4.0
  clipboard: ^0.1.3
  fade_shimmer: ^2.2.0
  dropdown_search: ^6.0.2
  flutter_paystack:
    git:
      url: https://github.com/mik3yyy/flutter_paystack.git
      ref: main
  paystack_standard: ^0.0.8
  top_snackbar_flutter: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 
  flutter_lints: ^5.0.0

  hive_generator: 
  flutter_gen_runner: 

flutter_gen:
  output: lib/core/gen/ # Optional (default: lib/core/gen/)
  line_length: 80 # Optional (default: 80)

  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

flutter:
  uses-material-design: true

  assets:
    - .env
    - application/assets/
    - application/assets/images/
    - application/assets/svgs/
    - application/assets/images/onboarding_images/
    - application/assets/fonts/
    - application/assets/fonts/Outfit/
    - application/assets/fonts/playfair/

  fonts:
    - family: Montserrat
      fonts:
        - asset: application/assets/fonts/Montserrat-Thin.ttf
          weight: 100
        - asset: application/assets/fonts/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: application/assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: application/assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: application/assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: application/assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: application/assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: application/assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: application/assets/fonts/Montserrat-Black.ttf
          weight: 900
    - family: Outfit
      fonts:
        - asset: application/assets/fonts/outfit/Outfit-ExtraLight.ttf
          weight: 200
        - asset: application/assets/fonts/outfit/Outfit-Regular.ttf
          weight: 400
        - asset: application/assets/fonts/outfit/Outfit-Medium.ttf
          weight: 500
        - asset: application/assets/fonts/outfit/Outfit-SemiBold.ttf
          weight: 600
        - asset: application/assets/fonts/outfit/Outfit-Bold.ttf
          weight: 700
        - asset: application/assets/fonts/outfit/Outfit-ExtraBold.ttf
          weight: 800
        - asset: application/assets/fonts/outfit/Outfit-Black.ttf
          weight: 900
    - family: PlayfairDisplay
      fonts:
        - asset: application/assets/fonts/playfair/PlayfairDisplay-Black.ttf
          weight: 200
        - asset: application/assets/fonts/playfair/PlayfairDisplay-Regular.ttf
          weight: 400
        - asset: application/assets/fonts/playfair/PlayfairDisplay-Medium.ttf
          weight: 500
        - asset: application/assets/fonts/playfair/PlayfairDisplay-SemiBold.ttf
          weight: 600
        - asset: application/assets/fonts/playfair/PlayfairDisplay-Bold.ttf
          weight: 700
        - asset: application/assets/fonts/playfair/PlayfairDisplay-ExtraBold.ttf
          weight: 800
        - asset: application/assets/fonts/playfair/PlayfairDisplay-Black.ttf
          weight: 900

